# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-02-13T22:47:55+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Features(BaseModel):
    NBR_ADDRESSES: int = Field(..., title='Nbr Addresses')
    NBR_ORDERS: int = Field(..., title='Nbr Orders')
    NBR_RX: int = Field(..., title='Nbr Rx')
    NBR_APT: int = Field(..., title='Nbr Apt')
    METRO_X: float = Field(..., title='Metro X')
    METRO_Y: float = Field(..., title='Metro Y')
    METRO_Z: float = Field(..., title='Metro Z')
    APT_FLG: int = Field(..., title='Apt Flg')
