use crate::core::agentic::schema::{ArtifactMeta, MapResponse};
use crate::core::auth::schema::{
    Authenticated, LoginRequest, LoginResponse, LogoutResponse, SsoAuthUrl, SsoCallbackParams,
};
use crate::core::capabilities::route::{
    AgenticInfo, AuthInfo, CapabilitiesResponse, DocumentationInfo, FeaturesInfo,
};
use crate::core::cards::schema::{
    CreateReadeMe, DashboardStatsResponse, FilterSummary, PageInfo, QueryPageResponse, ReadeMe,
    RegistryStatsResponse, VersionPageResponse,
};
use crate::core::debug::schema::DebugInfo;
use crate::core::docs::route::{
    DocListResponse, DocResponse, DocSummary, SearchResponse, SearchResult,
};
use crate::core::error::OpsmlServerError;
use crate::core::experiment::types::GroupedMetric;
use crate::core::user::schema::{
    CreateUserRequest, CreateUserResponse, CreateUserUiResponse, RecoveryResetRequest,
    ResetPasswordResponse, UpdateUserRequest, UserListResponse, UserResponse,
};
use opsml_types::{
    StorageType,
    api::types::{Alive, JwtToken},
    cards::{CPUMetrics, HardwareMetrics, MemoryMetrics, Metric, NetworkRates, Parameter},
    contracts::{
        ArtifactKey, ArtifactKeyRequest, ArtifactQueryArgs, ArtifactRecord, CardCursor,
        CardQueryArgs, CardSpaceResponse, CardTagsResponse, CompareHashRequest,
        CompareHashResponse, CompleteMultipartUpload, CreateArtifactRequest,
        CreateArtifactResponse, CreateCardResponse, CrudSpaceRequest, CrudSpaceResponse,
        DashboardStats, DeleteCardRequest, DeleteFileQuery, DeleteFileResponse, DownloadFileQuery,
        FileInfo, FileTreeNode, FileTreeResponse, GetHardwareMetricRequest, GetMetricNamesRequest,
        GetMetricNamesResponse, GetMetricRequest, GetParameterRequest, HardwareMetricRequest,
        HardwareMetricResponse, InvokeMetadata, InvokeRequest, InvokeResponse, JobStatus,
        ListFileInfoResponse, ListFileQuery, ListFileResponse, McpServers, MetricRequest,
        MetricResponse, MultiPartQuery, MultiPartSession, ParameterRequest, ParameterResponse,
        PresignedQuery, PresignedUrl, QueryPageRequest, RawFile, RawFileRequest,
        RegistrySpaceRequest, RegistryStatsRequest, ServiceQueryArgs, ServiceType, SpaceRecord,
        SpaceRecordResponse, SpaceStats, SpaceStatsResponse, StorageSettings, UiSettings,
        UidRequest, UidResponse, UpdateCardResponse, UploadResponse, VersionCursor,
        VersionPageRequest, skill::MarketplaceStats,
    },
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        // docs
        crate::core::docs::route::list_docs,
        crate::core::docs::route::get_doc,
        crate::core::docs::route::search_docs,
        crate::core::docs::route::list_examples,
        crate::core::docs::route::get_example,
        // capabilities
        crate::core::capabilities::route::capabilities,
        // health
        crate::core::health::route::health_check,
        // debug
        crate::core::debug::route::debug_info,
        // settings
        crate::core::settings::route::storage_settings,
        crate::core::settings::route::ui_settings,
        // genai
        crate::core::genai::route::list_mcp_servers,
        // auth
        crate::core::auth::route::api_login_handler,
        crate::core::auth::route::ui_logout_handler,
        crate::core::auth::route::ui_login_handler,
        crate::core::auth::route::api_refresh_token_handler,
        crate::core::auth::route::validate_jwt_token,
        crate::core::auth::route::get_sso_authorization_url,
        crate::core::auth::route::exchange_callback_token,
        crate::core::auth::route::register_user_from_ui,
        crate::core::auth::route::reset_password_with_recovery,
        // user
        crate::core::user::route::create_user,
        crate::core::user::route::list_users,
        crate::core::user::route::get_user,
        crate::core::user::route::update_user,
        crate::core::user::route::delete_user,
        // agentic
        crate::core::agentic::agent_route::invoke_agent,
        crate::core::agentic::agent_route::get_agent_job,
        crate::core::agentic::route::get_skill_latest,
        crate::core::agentic::route::get_skill_pinned,
        crate::core::agentic::route::get_skill_map,
        crate::core::agentic::route::get_featured_skills,
        crate::core::agentic::route::get_all_tags,
        crate::core::agentic::route::get_marketplace_stats,
        crate::core::agentic::route::get_subagent_latest,
        crate::core::agentic::route::get_subagent_pinned,
        crate::core::agentic::route::get_tool_latest,
        crate::core::agentic::route::get_tool_pinned,
        // cards
        crate::core::cards::route::check_card_uid,
        crate::core::cards::route::get_registry_spaces,
        crate::core::cards::route::get_registry_tags,
        crate::core::cards::route::get_all_space_stats,
        crate::core::cards::route::get_space_record,
        crate::core::cards::route::create_space_record,
        crate::core::cards::route::update_space_record,
        crate::core::cards::route::delete_space_record,
        crate::core::cards::route::retrieve_registry_stats,
        crate::core::cards::route::retrieve_dashboard_stats,
        crate::core::cards::route::retrieve_page,
        crate::core::cards::route::query_version_page,
        crate::core::cards::route::list_cards,
        crate::core::cards::route::create_card,
        crate::core::cards::route::update_card,
        crate::core::cards::route::delete_card,
        crate::core::cards::route::load_card,
        crate::core::cards::route::get_card,
        crate::core::cards::route::get_readme,
        crate::core::cards::route::create_readme,
        crate::core::cards::route::compare_content_hash,
        // experiment
        crate::core::experiment::route::insert_metrics,
        crate::core::experiment::route::get_metrics,
        crate::core::experiment::route::get_grouped_metrics,
        crate::core::experiment::route::get_metric_names,
        crate::core::experiment::route::insert_parameters,
        crate::core::experiment::route::get_parameter,
        crate::core::experiment::route::insert_hardware_metrics,
        crate::core::experiment::route::get_hardware_metrics,
        // files
        crate::core::files::route::create_multipart_upload,
        crate::core::files::route::generate_presigned_url,
        crate::core::files::route::complete_multipart_upload,
        crate::core::files::route::upload_multipart,
        crate::core::files::route::list_files,
        crate::core::files::route::list_file_info,
        crate::core::files::route::file_tree,
        crate::core::files::route::get_file_for_ui,
        crate::core::files::route::get_files_for_ui,
        crate::core::files::route::delete_file,
        crate::core::files::route::download_file,
        crate::core::files::route::get_artifact_key,
        crate::core::files::route::create_artifact_record,
        crate::core::files::route::query_artifact_records,
        // scouter
        crate::core::scouter::alerts::drift_alerts,
        crate::core::scouter::alerts::update_alert_status,
        crate::core::scouter::drift::get_spc_drift,
        crate::core::scouter::drift::get_psi_drift,
        crate::core::scouter::drift::get_custom_drift,
        crate::core::scouter::drift::get_agent_task_metrics,
        crate::core::scouter::drift::get_agent_workflow_metrics,
        crate::core::scouter::agent::query_agent_eval_records,
        crate::core::scouter::agent::query_agent_eval_workflow,
        crate::core::scouter::agent::get_agent_tasks,
        crate::core::scouter::health::check_scouter_health,
        crate::core::scouter::profile::insert_drift_profile,
        crate::core::scouter::profile::update_drift_profile,
        crate::core::scouter::profile::update_drift_profile_status,
        crate::core::scouter::profile::profile_exists,
        crate::core::scouter::profile::get_drift_profiles_for_ui,
        crate::core::scouter::tags::entity_from_tags,
        crate::core::scouter::trace::get_paginated_traces,
        crate::core::scouter::trace::get_trace_spans,
        crate::core::scouter::trace::trace_metrics,
    ),
    components(
        schemas(
            // docs + capabilities
            DocListResponse,
            DocSummary,
            DocResponse,
            SearchResponse,
            SearchResult,
            CapabilitiesResponse,
            FeaturesInfo,
            DocumentationInfo,
            AgenticInfo,
            AuthInfo,
            OpsmlServerError,
            // health + debug + settings
            Alive,
            DebugInfo,
            StorageSettings,
            UiSettings,
            StorageType,
            // auth
            JwtToken,
            LoginRequest,
            LoginResponse,
            LogoutResponse,
            Authenticated,
            SsoAuthUrl,
            SsoCallbackParams,
            // user
            UserResponse,
            CreateUserRequest,
            CreateUserResponse,
            CreateUserUiResponse,
            UpdateUserRequest,
            UserListResponse,
            RecoveryResetRequest,
            ResetPasswordResponse,
            // agentic
            ArtifactMeta,
            MapResponse,
            InvokeRequest,
            InvokeResponse,
            InvokeMetadata,
            JobStatus,
            MarketplaceStats,
            // genai / mcp
            McpServers,
            ServiceQueryArgs,
            ServiceType,
            // cards
            UidRequest,
            UidResponse,
            RegistrySpaceRequest,
            CardSpaceResponse,
            CardTagsResponse,
            SpaceStats,
            SpaceStatsResponse,
            SpaceRecord,
            SpaceRecordResponse,
            CrudSpaceRequest,
            CrudSpaceResponse,
            RegistryStatsRequest,
            QueryPageRequest,
            CardCursor,
            VersionPageRequest,
            VersionCursor,
            CardQueryArgs,
            CreateCardResponse,
            UpdateCardResponse,
            DeleteCardRequest,
            CompareHashRequest,
            CompareHashResponse,
            DashboardStats,
            QueryPageResponse,
            PageInfo,
            FilterSummary,
            VersionPageResponse,
            RegistryStatsResponse,
            DashboardStatsResponse,
            ReadeMe,
            CreateReadeMe,
            // experiment
            MetricRequest,
            MetricResponse,
            GetMetricRequest,
            GetMetricNamesRequest,
            GetMetricNamesResponse,
            Metric,
            HardwareMetricRequest,
            HardwareMetricResponse,
            HardwareMetrics,
            CPUMetrics,
            MemoryMetrics,
            NetworkRates,
            ParameterRequest,
            ParameterResponse,
            GetParameterRequest,
            Parameter,
            GetHardwareMetricRequest,
            GroupedMetric,
            // files
            MultiPartQuery,
            MultiPartSession,
            PresignedQuery,
            PresignedUrl,
            ListFileQuery,
            ListFileResponse,
            ListFileInfoResponse,
            FileInfo,
            FileTreeResponse,
            FileTreeNode,
            DeleteFileQuery,
            DeleteFileResponse,
            DownloadFileQuery,
            CompleteMultipartUpload,
            UploadResponse,
            ArtifactKeyRequest,
            ArtifactKey,
            ArtifactQueryArgs,
            ArtifactRecord,
            CreateArtifactRequest,
            CreateArtifactResponse,
            RawFileRequest,
            RawFile,
        )
    ),
    tags(
        (name = "docs", description = "Embedded documentation and Python examples — no auth required"),
        (name = "capabilities", description = "Server capability index and endpoint discovery — no auth required"),
        (name = "health", description = "Server liveness check — no auth required"),
        (name = "debug", description = "Runtime diagnostics — no auth required"),
        (name = "settings", description = "Storage and UI feature flag settings — no auth required"),
        (name = "auth", description = "Authentication — login, logout, token refresh, SSO, and password recovery"),
        (name = "user", description = "User management — create, read, update, delete users"),
        (name = "agentic", description = "Agentic primitives — invoke agents, browse skills, subagents, tools, and marketplace"),
        (name = "genai", description = "GenAI service registry — MCP server discovery"),
        (name = "cards", description = "Card registry — create, list, load, update, delete versioned artifact cards"),
        (name = "experiment", description = "Experiment tracking — metrics, parameters, and hardware telemetry"),
        (name = "files", description = "File storage — multipart upload, download, presigned URLs, file listings"),
        (name = "scouter", description = "Drift monitoring and observability via Scouter integration"),
    ),
    info(
        title = "OpsML API",
        version = "1.0.0",
        description = "AI lifecycle platform — cards, experiments, and agentic primitives. \
            All protected endpoints require a Bearer JWT obtained from POST /opsml/api/auth/ui/login. \
            Start with GET /opsml/api/v1/capabilities to discover available endpoints."
    )
)]
pub struct ApiDoc;
