CREATE TABLE IF NOT EXISTS opsml_mcp_registry (
    uid TEXT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    app_env TEXT DEFAULT 'development',
    space TEXT,
    name TEXT,
    major INT NOT NULL,
    minor INT NOT NULL,
    patch INT NOT NULL,
    pre_tag TEXT,
    build_tag TEXT,
    version TEXT,
    cards TEXT DEFAULT '[]',
    opsml_version TEXT NOT NULL DEFAULT '0.0.0',
    username TEXT NOT NULL DEFAULT 'guest',
    service_type TEXT NOT NULL DEFAULT 'mcp',
    metadata TEXT,
    deployment TEXT,
    service_config TEXT,
    tags TEXT
);