[package]
name = "opsml-utils"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false

[dependencies]
opsml-error = { workspace = true }
chrono = { workspace = true }
pyo3 = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }