CREATE TABLE IF NOT EXISTS opsml_mcp_registry (
    uid VARCHAR(64) PRIMARY KEY,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    app_env VARCHAR(32) DEFAULT 'development',
    space VARCHAR(255),
    name VARCHAR(255),
    major INT NOT NULL,
    minor INT NOT NULL,
    patch INT NOT NULL,
    pre_tag VARCHAR(255),
    build_tag VARCHAR(255),
    version VARCHAR(255),
    cards JSON NOT NULL DEFAULT ('[]'),
    opsml_version VARCHAR(255) NOT NULL DEFAULT '0.0.0',
    username VARCHAR(255) NOT NULL DEFAULT 'guest',
    service_type VARCHAR(32) NOT NULL DEFAULT 'api',
    metadata JSON,
    deployment JSON,
    service_config JSON,
    tags JSON
);