# mypy: disable-error-code="attr-defined"
# python/opsml/card/__init__.py
from .._opsml import (
    AgentCapabilities,
    AgentCardSignature,
    AgentExtension,
    AgentInterface,
    AgentProvider,
    AgentSkill,
    AgentSkillStandard,
    AgentSpec,
    ApiKeySecurityScheme,
    AuthorizationCodeFlow,
    Card,
    CardList,
    CardRecord,
    CardRegistries,
    CardRegistry,
    ClientCredentialsFlow,
    ComputeEnvironment,
    DataCard,
    DataCardMetadata,
    DependencyKind,
    DeviceCodeFlow,
    ExperimentCard,
    HttpAuthSecurityScheme,
    ImplicitAuthFlow,
    ModelCard,
    ModelCardMetadata,
    MtlsSecurityScheme,
    Oauth2SecurityScheme,
    OAuthFlows,
    OpenIdConnectSecurityScheme,
    PassWordAuthFlow,
    PromptCard,
    ProtocolBinding,
    RegistryMode,
    RegistryType,
    SecurityRequirement,
    SecurityScheme,
    ServiceCard,
    SkillCard,
    SkillDependency,
)


class AgentCard(ServiceCard):
    """AgentCard represents a card that defines an agent,
    including its capabilities, skills, and interfaces.
    """


__all__ = [
    "Card",
    "CardRecord",
    "CardList",
    "CardRegistry",
    "CardRegistries",
    "DataCard",
    "DataCardMetadata",
    "RegistryType",
    "RegistryMode",
    "ModelCard",
    "ModelCardMetadata",
    "ExperimentCard",
    "ComputeEnvironment",
    "PromptCard",
    "ServiceCard",
    "AgentCard",
    "AgentProvider",
    "AgentInterface",
    "AgentExtension",
    "AgentCapabilities",
    "SecurityRequirement",
    "AgentSkill",
    "ApiKeySecurityScheme",
    "HttpAuthSecurityScheme",
    "MtlsSecurityScheme",
    "Oauth2SecurityScheme",
    "OpenIdConnectSecurityScheme",
    "SecurityScheme",
    "OAuthFlows",
    "AuthorizationCodeFlow",
    "ClientCredentialsFlow",
    "DeviceCodeFlow",
    "ImplicitAuthFlow",
    "PassWordAuthFlow",
    "AgentCardSignature",
    "AgentSkillStandard",
    "AgentSpec",
    "DependencyKind",
    "ProtocolBinding",
    "SkillCard",
    "SkillDependency",
]
