[package]
name = "opsml-types"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false


[dependencies]
chrono = { workspace = true }
opsml-colors = { workspace = true }
opsml-crypt = { workspace = true }
opsml-semver = { workspace = true }
opsml-utils = { workspace = true }
opsml-version = { workspace = true }
potato-head = { workspace = true }
scouter-client = { workspace = true }
semver = { workspace = true }
pyo3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = { workspace = true }
tabled = { workspace = true, features = ["ansi"] }
thiserror = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true, optional = true }


[features]
default = []
server = ["sqlx"]
