# mypy: disable-error-code="attr-defined"
# pylint: disable=no-name-in-module
# python/opsml/__init__.py
from . import (
    app,
    card,
    data,
    evaluate,
    experiment,
    genai,
    logging,
    mock,
    model,
    scouter,
    types,
)
from ._opsml import (  # top-level modules; # App; # Card; # Data; Experiment; # model
    AppState,
    ArrowData,
    Card,
    CardRegistries,
    CardRegistry,
    CatBoostModel,
    DataCard,
    DataInterface,
    Experiment,
    HuggingFaceModel,
    HuggingFaceOnnxArgs,
    HuggingFaceORTModel,
    HuggingFaceTask,
    LightGBMModel,
    LightningModel,
    ModelCard,
    ModelInterface,
    ModelLoadKwargs,
    ModelSaveKwargs,
    NumpyData,
    PandasData,
    PolarsData,
    PromptCard,
    RegistryType,
    ReloadConfig,
    ServiceCard,
    SklearnModel,
    SqlData,
    TaskType,
    TensorFlowModel,
    TorchModel,
    XGBoostModel,
    get_opsml_version,
    start_experiment,
)

__version__: str = get_opsml_version()

__all__ = [
    "types",
    "card",
    "data",
    "model",
    "experiment",
    "evaluate",
    "app",
    "logging",
    "mock",
    "scouter",
    "genai",
    "cli",
    ## App
    "AppState",
    "ReloadConfig",
    ## Card
    "Card",
    "CardRegistries",
    "CardRegistry",
    "DataCard",
    "ModelCard",
    "PromptCard",
    "ServiceCard",
    "RegistryType",
    ## Data
    "DataInterface",
    "NumpyData",
    "PandasData",
    "PolarsData",
    "SqlData",
    "ArrowData",
    # Experiment
    "start_experiment",
    "Experiment",
    ## model
    "ModelInterface",
    "ModelLoadKwargs",
    "ModelSaveKwargs",
    "SklearnModel",
    "TaskType",
    "TensorFlowModel",
    "TorchModel",
    "XGBoostModel",
    "HuggingFaceModel",
    "HuggingFaceOnnxArgs",
    "HuggingFaceORTModel",
    "HuggingFaceTask",
    "LightGBMModel",
    "LightningModel",
    "CatBoostModel",
    "__version__",
]
