#!/usr/bin/env bash
# OpsML skill sync startup hook — generated by: opsml configure --lazy
OPSML_BIN=__OPSML_BIN__
SKILLS_YAML="${HOME}/.opsml/skills.yaml"
MANIFEST="${HOME}/.opsml/cache/manifest.json"

# Guard: opsml must be reachable
command -v "$OPSML_BIN" >/dev/null 2>&1 || exit 0

# Read TTL from the project yaml (absolute path embedded at configure time)
TTL_MINUTES=$(grep -m1 'ttl_minutes' "$SKILLS_YAML" 2>/dev/null | awk '{print $2}' | sed 's/#.*//' | tr -d ' ')
TTL_MINUTES=${TTL_MINUTES:-60}

# Check cache freshness only when jq is available; otherwise fall through to sync
if command -v jq >/dev/null 2>&1; then
    GENERATED_AT=$(jq -r '.generated_at // empty' "$MANIFEST" 2>/dev/null)
    if [ -n "$GENERATED_AT" ]; then
        # GNU date (Linux) vs BSD date (macOS) — force UTC via Z suffix on BSD path
        if date --version >/dev/null 2>&1; then
            FETCHED=$(date -d "$GENERATED_AT" +%s 2>/dev/null || echo 0)
        else
            local_ts="${GENERATED_AT%Z}"
            local_ts="${local_ts%%.*}"
            FETCHED=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "${local_ts}Z" +%s 2>/dev/null || echo 0)
        fi
        NOW=$(date +%s)
        AGE=$(( NOW - FETCHED ))
        [ "$AGE" -lt $(( TTL_MINUTES * 60 )) ] && exit 0
    fi
fi

# Run in background — must not block the session start
# sync handles both global and project layers automatically
"$OPSML_BIN" skill sync --quiet &
exit 0
