#!/usr/bin/env bash
# OpsML skill sync startup hook — generated by: opsml configure --lazy
MANIFEST="${HOME}/.opsml/cache/manifest.json"
TTL_MINUTES=$(grep -m1 'ttl_minutes' .opsml-skills.yaml 2>/dev/null | awk '{print $2}')
TTL_MINUTES=${TTL_MINUTES:-60}

if [ -f "$MANIFEST" ]; then
    GENERATED_AT=$(jq -r '.generated_at // empty' "$MANIFEST" 2>/dev/null || true)
    if [ -n "$GENERATED_AT" ]; then
        # GNU date (Linux) vs BSD date (macOS)
        if date --version >/dev/null 2>&1; then
            FETCHED=$(date -d "$GENERATED_AT" +%s 2>/dev/null || echo 0)
        else
            FETCHED=$(date -j -f "%Y-%m-%dT%H:%M:%S" "${GENERATED_AT%%.*}" +%s 2>/dev/null || echo 0)
        fi
        NOW=$(date +%s)
        AGE=$(( NOW - FETCHED ))
        [ "$AGE" -lt $(( TTL_MINUTES * 60 )) ] && exit 0
    fi
fi

# Run in background — must not block the session start
opsml skill sync --quiet &
exit 0
