# mypy: disable-error-code="attr-defined"
# pylint: disable=no-name-in-module
import importlib

from .._opsml import (
    AgentEvalConfig,
    AgentEvalProfile,
    AlertThreshold,
    AssertionTask,
    CommonCrons,
    ComparisonOperator,
    CustomDriftProfile,
    CustomMetric,
    CustomMetricAlertConfig,
    CustomMetricDriftConfig,
    DataProfile,
    DataProfiler,
    DatasetClient,
    DatasetProducer,
    Doane,
    Drifter,
    EqualWidthBinning,
    EvalRecord,
    EvalResults,
    FeatureMap,
    Features,
    FreedmanDiaconis,
    GrpcConfig,
    HttpConfig,
    KafkaConfig,
    LLMJudgeTask,
    Manual,
    Metric,
    Metrics,
    PsiAlertConfig,
    PsiDriftConfig,
    PsiDriftMap,
    PsiDriftProfile,
    QuantileBinning,
    QueryResult,
    Queue,
)
from .._opsml import QueueFeature as Feature
from .._opsml import (
    RabbitMQConfig,
    RedisConfig,
    Rice,
    Scott,
    ScouterClient,
    ScouterQueue,
    SpcAlertConfig,
    SpcDriftConfig,
    SpcDriftMap,
    SpcDriftProfile,
    SpcFeatureDrift,
    SpcFeatureDriftProfile,
    SquareRoot,
    Sturges,
    TableConfig,
    TerrellScott,
    WriteConfig,
)
from . import (
    alert,
    bifrost,
    client,
    drift,
    evaluate,
    observe,
    profile,
    queue,
    trace,
    tracing,
    transport,
    types,
    util,
)
from .bifrost import Bifrost


def __getattr__(name: str):
    if name == "service_map":
        module = importlib.import_module(".service_map", __name__)
        globals()[name] = module
        return module
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


__all__ = [
    "alert",
    "bifrost",
    "client",
    "drift",
    "evaluate",
    "observe",
    "profile",
    "queue",
    "tracing",
    "transport",
    "types",
    "util",
    "service_map",
    "trace",
    # top-level imports
    "Drifter",
    "SpcDriftConfig",
    "SpcDriftProfile",
    "SpcFeatureDriftProfile",
    "SpcFeatureDrift",
    "SpcDriftMap",
    "PsiDriftConfig",
    "PsiDriftProfile",
    "PsiDriftMap",
    "FeatureMap",
    "CustomMetric",
    "CustomDriftProfile",
    "CustomMetricDriftConfig",
    "QuantileBinning",
    "EqualWidthBinning",
    "Manual",
    "SquareRoot",
    "Sturges",
    "Rice",
    "Doane",
    "Scott",
    "TerrellScott",
    "FreedmanDiaconis",
    "DataProfiler",
    "DataProfile",
    "ScouterQueue",
    "Queue",
    "Feature",
    "Features",
    "Metric",
    "Metrics",
    "CommonCrons",
    "PsiAlertConfig",
    "SpcAlertConfig",
    "CustomMetricAlertConfig",
    "ScouterClient",
    "HttpConfig",
    "GrpcConfig",
    "KafkaConfig",
    "RabbitMQConfig",
    "RedisConfig",
    "AlertThreshold",
    # bifrost
    "Bifrost",
    "DatasetClient",
    "DatasetProducer",
    "QueryResult",
    "TableConfig",
    "WriteConfig",
    # agent
    "AgentEvalConfig",
    "AgentEvalProfile",
    "EvalRecord",
    "LLMJudgeTask",
    "AssertionTask",
    "ComparisonOperator",
    "EvalResults",
]
