# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on: push

# permission can be added at job level or workflow level

jobs:
  S3PackageUpload:
    permissions:
      id-token: write
      contents: read
    env:
      BUCKET_NAME: "${{ secrets.AWS_S3_BUCKET }}"
      AWS_REGION: "${{ secrets.AWS_REGION }}"
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::360571623544:role/opsml-integration-oidc
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: Copy index.html to s3
        run: |
          aws s3 cp ./LICENSE.md s3://${{ env.BUCKET_NAME }}/

  AZURE-Integration:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run az commands"
        run: |
          az account show
          az group list
