name: Publish-Github-Pages

on:
  push:
    branches:
      - main

  release:
    types: [published]

env:
  PYTHON_VERSION: "3.12"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  BuildDocs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          ignore-nothing-to-cache: true

      - name: Install Protocol Buffers Compiler
        uses: arduino/setup-protoc@v3
        with:
          version: "33.2"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev pkg-config

      - name: Build Docs
        working-directory: ./py-opsml
        run: |
          make setup.docs
          make publish.docs
